spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/p6spy
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: info

decorator:
  datasource:
    p6spy:
      enable-logging: true